In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/HR Employee attrition analytics /WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [3]:
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [4]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [5]:
df2=df[df['EmployeeCount']!=1]
df2

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]

In [6]:
#dropping Employee count column as all employees have that field set to 1 and it's given knowledge
#also dropping Over18 as the information can be deduced during run time using Age field
df=df.drop(columns=['EmployeeCount','Over18'])

In [7]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,4,80,1,6,3,3,2,2,2,2

In [8]:
#median salary calculation from data set for various roles .
df['Role_Median_Salary'] = df.groupby('JobRole')['MonthlyIncome'].transform('median') #broadcast using transform
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,80,0,8,0,1,6,4,0,5,6231.0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,80,1,10,3,3,10,7,1,7,2887.5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,80,0,7,3,3,0,0,0,0,2886.0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,80,0,8,3,3,8,7,3,0,2887.5
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,80,1,6,3,3,2,2,2,2,2886.0

In [10]:
# over_worked flag rule : less than two years and working overtime | selected two years because that is when bonuses stock on median can be cashed out
df['flag_overworked']=(df['OverTime']=='Yes') & (df['YearsAtCompany'] <=2)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary,flag_overworked
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,0,8,0,1,6,4,0,5,6231.0,False
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,1,10,3,3,10,7,1,7,2887.5,False
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,7,3,3,0,0,0,0,2886.0,True
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,0,8,3,3,8,7,3,0,2887.5,False
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,1,6,3,3,2,2,2,2,2886.0,False

In [11]:
# underpaid rule set by pay less than median salary we determined above
df['flag_underpaid']=df['MonthlyIncome']<df['Role_Median_Salary']
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary,flag_overworked,flag_underpaid
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,8,0,1,6,4,0,5,6231.0,False,True
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,10,3,3,10,7,1,7,2887.5,False,False
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,7,3,3,0,0,0,0,2886.0,True,True
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,8,3,3,8,7,3,0,2887.5,False,False
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,6,3,3,2,2,2,2,2886.0,False,False

In [12]:
#role satisfaction rule : if user has been in a role for more than three years and job satisfaction score is less than 2
df['flag_stagnate']=(df['YearsInCurrentRole']>3)&(df['JobSatisfaction']<=2)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary,flag_overworked,flag_underpaid,flag_stagnate
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,0,1,6,4,0,5,6231.0,False,True,False
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,3,3,10,7,1,7,2887.5,False,False,True
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,3,3,0,0,0,0,2886.0,True,True,False
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,3,8,7,3,0,2887.5,False,False,False
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,3,3,2,2,2,2,2886.0,False,False,False

In [13]:
#chronic job hopper identifier : worked in more than 4 jobs before here and the 2 year mark is approaching
df['flag_hopper']=(df['NumCompaniesWorked']>=4)&(df['YearsAtCompany']<2)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary,flag_overworked,flag_underpaid,flag_stagnate,flag_hopper
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,1,6,4,0,5,6231.0,False,True,False,False
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,3,10,7,1,7,2887.5,False,False,True,False
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,3,0,0,0,0,2886.0,True,True,False,True
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,3,8,7,3,0,2887.5,False,False,False,False
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,3,2,2,2,2,2886.0,False,False,False,False

In [14]:
#high risk column : if any flags are true in temp dataframe created out of new flags , then we can deem user at high risk
df['High_Risk'] = df[['flag_overworked', 'flag_underpaid',  'flag_stagnate', 'flag_hopper']].any(axis=1)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Role_Median_Salary,flag_overworked,flag_underpaid,flag_stagnate,flag_hopper,High_Risk
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,6,4,0,5,6231.0,False,True,False,False,True
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,10,7,1,7,2887.5,False,False,True,False,True
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,0,0,0,0,2886.0,True,True,False,True,True
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,8,7,3,0,2887.5,False,False,False,False,False
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,2,2,2,2,2886.0,False,False,False,False,False

## Our Rule-Based Analysis

In [15]:
total_employees=len(df)
total_at_risk=df['High_Risk'].sum()
print("Predicted At Risk :",total_at_risk," employees ,out of ",total_employees," employees")
print("High risk percentage:",((total_at_risk*100)/total_employees))

Predicted At Risk : 960  employees ,out of  1470  employees
High risk percentage: 65.3061224489796

## Moment of Truth : Comparison results between our rules' outcome and reality

In [16]:
comparison=pd.crosstab(df['Attrition'],df['High_Risk'], margins=True)
print("Actual attrition vs High-Risk Flag created:")
print(comparison)

Actual attrition vs High-Risk Flag created:
High_Risk  False  True   All
Attrition
No           446   787  1233
Yes           64   173   237
All          510   960  1470

In [17]:
actual_quit_rate = df[df['High_Risk'] == True]['Attrition'].value_counts(normalize=True) * 100
print("\nPercentage of your flagged employees who actually quit:")
print(actual_quit_rate)

Percentage of your flagged employees who actually quit:
Attrition
No     81.979167
Yes    18.020833
Name: proportion, dtype: float64

## exporting data

In [20]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/HREmployeeAttrition/hr_attrition_cleaned.csv', index=False)
print("CSV exported successfully")

CSV exported successfully